id = "stylus"
name = "Stylus"
description = "Stylus (.styl) language support"
version = "0.1.0"
schema_version = 1
authors = ["sf-yuzifu"]
repository = "https://github.com/sf-yuzifu/stylus-zed"

[grammars.stylus]
repository = "https://github.com/sf-yuzifu/tree-sitter-stylus"
rev = "c05916f9d5e4202b81ec8c2eb7885f99ed9014df"
